# -*- coding: utf-8 -*-
"""Face crop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CUof3vAM0kAkQ_uL5KKZBbY8I4UKQMNw

# New Section
"""

from google.colab import drive
drive.mount('/content/drive')

import glob 
import cv2
import sys
import os
def detect_face(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    face_cascade = cv2.CascadeClassifier('/content/drive/My Drive/Research project/haarcascade_frontalface_default.xml')
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.2, minNeighbors=5)
    return faces

filename = "/content/drive/My Drive/TestingData/pain/4"

for img in glob.glob(filename+'/*.*'):
    var_img = cv2.imread(img)
    face = detect_face(var_img)
    print(face)
    if (len(face) == 0):
        continue
    for(ex, ey, ew, eh) in face:
        crop_image = var_img[ey:ey+eh, ex:ex+ew]
        #cv2.imshow("cropped", crop_image)
        cv2.waitKey(0)  
    cv2.imwrite(os.path.join("/content/drive/My Drive/Face_cropP1",str(img)),crop_image)